#!/bin/sh
# always stop
killall syslogd >> /dev/null 2>&1
if [ "$1" = "stop" ]; then
	echo "$0: Stoped syslogd."
else
	echo "$0: Starting syslogd ..."
	logsize=`nvram get syslogd_logsize_kb`
	echo "$0: logsize=$logsize"
	if [ ! $logsize ]; then
		logsize="16"
	fi
	mark_interval=`nvram get syslogd_mark_min`	
	if [ ! $mark_interval ]; then
		mark_interval="0"
	fi	
	echo "$0: mark_interval=$mark_interval"
	log_ipaddr=`nvram get log_ipaddr`
	if [ ! $log_ipaddr ]; then
		remote_cmdline=""
	else
		echo "remote"
		remote_cmdline="-R $log_ipaddr"
	fi
	syslogd -C "$logsize" -m "$mark_interval" "$remote_cmdline" &
fi
